DeviceFarmer/stf

lib/units/device/resources/minicap.js
lib/units/device/resources/minitouch.js

Signed-off-by: Karol Wrótniak <karol.wrotniak@droidsonroids.pl>

Fix prebulit binaries paths

---

lib/units/device/resources/minicap.js
lib/units/device/resources/minitouch.js

Signed-off-by: Karol Wrótniak <karol.wrotniak@droidsonroids.pl>

Add @devicefarmer to prebulit binaries paths

---

lib/units/app/index.js

Signed-off-by: Karol Wrótniak <karol.wrotniak@droidsonroids.pl>

Add @devicefarmer to stf-wiki path

---

lib/units/app/middleware/appstore-icons.js
lib/units/app/middleware/browser-icons.js
lib/units/app/middleware/device-icons.js

Fix images

---

package.json

minicap 2.5.0
adbkit 2.11.3
adbkit-apkreader 3.2.2

Dependency versions bump

---

Dockerfile-debian-x86_64

- Update "LABEL Url" from openstf to devicefarmer
Signed-off-by: Denis barbaron denis.barbaron@orange.com

Update Dockerfile for Debian x86_64

---

Dockerfile-debian-armhf

- update "LABEL Url" from openstf to devicefarmer
- install "cmake" package
Signed-off-by: Denis barbaron <denis.barbaron@orange.com>

Update Dockerfile for Debian armhf

---

README.md
docker-compose.yaml

Signed-off-by: Ian Foster <ian@vorsk.com>
Retrying #151 with correct signoff.

Added simple docker-compose example

---

README.md

[skip-ci] Add cmake to dependency list

---

lib/units/provider/index.js

Fixes https://github.com/DeviceFarmer/adbkit/issues/90

Fix adbkit invocation

---

Dockerfile-debian-armhf

add --legacy-peer-deps to avoid dependency error.

Fix build error on arm platform

---

bower.json

Changed ng-context-menu coordinates

---

Dockerfile-debian-armhf

Signed-off-by: Denis Barbaron <denis.barbaron@orange.com>

upgrade from stretch to buster the Docker image for armhf

---

package.json

Signed-off-by: Denis Barbaron <denis.barbaron@orange.com>

update minicap-prebuilt version to 2.7.1

---

lib/util/devutil.js
package.json

hi 
if you have any objections or suggestions against PR, i can the update the code 
thanx

stf: Device name related updates

---

lib/cli/provider/index.js

Signed-off-by: Denis barbaron <denis.barbaron@orange.com>

fix bug on screen grabber management

---

lib/cli/device/index.js
lib/cli/provider/index.js
lib/units/device/plugins/screen/stream.js

Signed-off-by: Denis barbaron <denis.barbaron@orange.com>

add frame rate management

---

lib/util/devutil.js
yarn.lock

According to research, the marketName associated with the Android device did not come out because the related model was not filtered.
Signed-off-by: Joowon Moon <jsjs401@daum.net>

fix #592 Fix marketName issue

---

docker-compose.yaml

Update rethinkdb to 2.4.2 in docker compose sample

---

README.md

Thanks to @dev-jonghoonpark (#679)

fix docker url of STF

---

Dockerfile-debian-arm64

This is a minor cosmetic change. Missed this in https://github.com/DeviceFarmer/stf/pull/712.

Fix the description in Dockerfile-debian-arm64

---

lib/units/device/resources/service.js

@koral-- , the STFService.apk under vendor folder is well the 2.4.12 version ?

Update STF Service APK to 2.4.12

---

lib/db/api.js
lib/units/auth/mock.js

This PR fixes the bug which allows changing the name of a user already created in the database, which causes inconsistency problems in the database and in user views

fix bug on user name management

---

.semaphore/deploy_dockerhub.yml
.semaphore/semaphore.yml
Dockerfile

Add support for arm64 to Dockerfile

---

lib/units/api/controllers/user.js

strengthens lock when taking control of a device (see history in PR #650 )

fix bug by completing the PR #650

---

CHANGELOG.md
package.json

Update changelog, fix version number consistency

---

README.md
lib/cli/migrate/index.js
lib/db/api.js

Now it is possible to change the administrator identity over time without having to reset the database

update built-in objects in the database

---

package.json

now 0 vulnerabilities on production mode

fix security issues
