DeviceFarmer/stf

res/app/control-panes/explorer/explorer-controller.js

While getting a file on a controlled device, the connection to minicap service was stopping due to the URL redirection.
Signed-off-by: Denis barbaron <denis.barbaron@orange.com>

Fix issue on File Explorer

---

lib/util/bundletool.js

Fixed #136 AAB installation fails when /tmp is on different mountpoint than storage-temp save directory
Signed-off-by: nghia.viminh <nghia.viminh@gameloft.com>

Fix AAB installation

---

lib/units/api/controllers/devices.js
lib/units/api/swagger/api_v1.yaml

PR introduce new REST API for update device note using PUT method.
Covers #216

add rest API for update Device note

---

lib/units/device/plugins/screen/stream.js

Some devices (Pixel 4XL) need more time to retrieve PID, in such cases when the retrieval failed - the whole stream is shutting down, therefore, connection with Minicap is lost which leads to constant empty screen on the Web UI.
Here's the problem described: https://github.com/DeviceFarmer/minicap/issues/17#issuecomment-1022889815

:bug: Fix: Increase PID retrieval timeout for edge-cases

---

.semaphore/deploy_dockerhub.yml
.semaphore/deploy_npmjs.yml
.semaphore/semaphore.yml

Signed-off-by: Denis Barbaron <denis.barbaron@orange.com>
@koral-- , in short I have upgraded Ubuntu and node versions, and add python3 package, but I have no way to test this PR, I let you correct my mistakes if any

update semaphore files for consistency with upgrading node to latest tag

---

yarn.lock

If the user does not have a generated ssh key pair, then getting from github via ssh fails with an error:
```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/fintechx/swagger-node-runner.git
npm ERR! Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
```

Fixing the link to get the package swagger-node-runner from ssh to https

---

res/app/components/stf/device/enhance-device/enhance-device-service.js

In this PR was added possibility to display correct device market name instead of "more technical" model name
An example:

Enable device market name

---

res/app/control-panes/device-control/device-control.css

Using css moved off screen the password autofill form when trying to use keyboard

move off screen password autofill

---

lib/db/api.js
lib/units/api/controllers/user.js
lib/util/lockutil.js

It fixes the #620 issue at API level

fix bug on taking control of a device: set a lock for exclusive access

---

res/app/control-panes/explorer/index.js

Noticed on my Samsung Galaxy device some directories were not being recognized as directories in the explorer.  They have different modes, such as 17913 so they aren't equal to 0o40000 even after subtracting the 0o777 to remove the perms.  Looked around and found the header file containing the macros used by commands such as stat: [stat.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/stat.h#L9-L27).
Just updated the logic of `isDir` to use the bit mask like stat does to capture directories with other flags set.  Also updated the `formatPermissionMode` in the same way and added `l` for symlinks

Explorer directory fix

---

Dockerfile-debian-arm64

Image can be built on a normal x86_64 linux PC with installed qemu-aarch64-static and properly configured binfmt_misc by running
docker build --platform linux/arm64/v8 -f Dockerfile-debian-arm64 -t stf .
or
buildah bud --platform linux/arm64/v8 -f Dockerfile-debian-arm64 -t stf .

Add Dockerfile for arm64

---

lib/cli/local/index.js

I use `stf` for a very small installation with just one user and few devices. `stf local` provides enough functionality and is easy to run: just one command without the need to configure all internal services separately. The only missing feature is the ability to provide access securely over the internet.
I want to use nginx reverse proxy with https and client certificate authorization, but currently this does not play well with modern browsers as they refuse to connect to insecure ws:// from secure https:// context.
This patch just adds the ability to configure various URL patterns to match the externally accessible address of the installation.

Add more CLI options for `stf local` to support reverse proxies

---

res/app/components/stf/browser-info/browser-info-service.js

Currently, enabling the "Desktop site" mode in Chrome on Android does nothing to the stf interface.

Fix mobile browser detection so that "Desktop mode" works as expected

---

lib/units/app/index.js

When using STF in HTTPS mode, cookies marked "httpOnly" cannot be deleted by the client-side STF web application, resulting in incorrect session closure at logout stage, this PR allows so this delete NOW.

fix bug on cookie using https

---

lib/units/device/index.js
lib/units/device/plugins/bluetooth.js
lib/units/device/plugins/service.js
lib/units/websocket/index.js
lib/wire/wire.proto
res/app/components/stf/control/control-service.js
res/app/control-panes/automation/device-settings/device-settings-controller.js
res/app/control-panes/automation/device-settings/device-settings.pug

Finish https://github.com/openstf/stf/pull/790 and taking care previous comments.
Looks like;
note: because of DCO requirements, had to rework original commits and decided to merged all to one commit.

Implement enable/disable bluetooth of devices

---

lib/units/device/plugins/bluetooth.js
lib/units/device/plugins/service.js
lib/units/websocket/index.js
lib/wire/wire.proto
res/app/components/stf/control/control-service.js
res/app/control-panes/automation/device-settings/device-settings-controller.js
res/app/control-panes/automation/device-settings/device-settings.pug

UI button to clean paired (bonded) bluetooth devices.
Based on https://github.com/DeviceFarmer/STFService.apk/pull/128 which is updated here in #755 .

UI support to cleanup bluetooth bonded devices

---

lib/cli/device/index.js
lib/cli/local/index.js
lib/cli/provider/index.js
lib/units/device/plugins/cleanup.js
lib/units/device/plugins/service.js

Two new CLI arguments for cleanup phase;
```shell
--cleanup-disable-bluetooth  Whether to disable Bluetooth during cleanup. [boolean] [default: false]
--cleanup-bluetooth-bonds    Whether to remove Bluetooth bonds during cleanup.  [boolean] [default: false]
```
This allows to ensure that phone are not bonded to devices after it's released.

options to disable bluetooth and/or clean bonded (paired) devices

---

lib/units/device/resources/service.js

add required permissions for new sdk:s to be able to use "find me" and bluetooth features.
tested with android14 and old android 9 phone.

grant STFService permissions to be able to use features

---

lib/cli/device/index.js
lib/cli/local/index.js
lib/cli/provider/index.js
lib/units/device/plugins/cleanup.js

To keep phones stable for longer duration, e.g. `/data/local/tmp` folder seem to be needed to cleanup every now and then. This was earlier done in separate apk/tool, but simpler to do it directly by `stf`, so bring such functionality natively here. If folder/file removing fails, error message are written to logs.  Cleanup ignore `stf` service files ( `minicap.apk, minicap, minicap.so, minitouch, minirev`).
NOTE: "fool detection" is very simple and it's easy to round up if user really want to make harm for phone. Feature is still deployment configuration so it's admin who can mess up devices, who normally won't do such thing, so I think it's okay. Currently provider raises at startup phase if one of following path are part of given cleanup-folder prefix; `/system, /boot, /proc, /vendor, …

option to cleanup tmp folder during cleanup phase

---

lib/units/device/resources/service.js
package.json

Set permissions based on SDK versions to ensure it works older phones
fix: #782
Tested with (including BLE features from UI)
- SDK34
- SDK28

fix SDK<34 STFService installation 

---

res/web_modules/nine-bootstrap/nine-bootstrap.scss

Using the latest LTS version of nodejs (20.17.0), some Sass deprecation warnings are generated at runtime, this has been fixed!

fix bug on deprecation warning using sass

---

lib/db/api.js
lib/units/processor/index.js
lib/units/provider/index.js
lib/units/websocket/index.js
lib/util/fakedevice.js
lib/wire/wire.proto

improve device state consistency

---

lib/units/device/resources/service.js

The progressed filter (?) stops DeviceFarmer from working both in a container and a bare-metal environment so this pr removes it.

fix: remove progressed from call as it prohibits the system from working

---

lib/cli/auth-saml2/index.js
lib/units/auth/saml2.js

improve saml authentication

---

lib/units/app/index.js
res/app/app.js
res/app/menu/menu.css
res/app/menu/menu.pug
res/test/e2e/menu/menu-spec.js

Adds the STF application version to the main menu in the Web UI.
Changes:
- Modified `lib/units/app/index.js` to read the version from `package.json` and make it available to the frontend via the `GLOBAL_APPSTATE.config.stfVersion` variable.
- Updated `res/app/menu/menu.pug` to display this version in the top navigation bar, near the help icon. The format is "vX.Y.Z".
- Added an E2E test (`res/test/e2e/menu/menu-spec.js`) to verify the presence and correct format of the version string in the UI.

feat: Display STF version in Web UI

---

lib/units/api/swagger/api_v1.yaml

/users/{email}/accessTokens API returns 201 when successful, not 200.
[lib/units/api/controllers/users.js#L421C10-L421C31](https://github.com/DeviceFarmer/stf/blob/eca8d78b707a3e05d6ad188bde7d5e7209c0d80c/lib/units/api/controllers/users.js#L421C10-L421C31)
[lib/units/api/controllers/user.js#L543](https://github.com/DeviceFarmer/stf/blob/eca8d78b707a3e05d6ad188bde7d5e7209c0d80c/lib/units/api/controllers/user.js#L543)

fix response status code of the createUserAccessToken API in swagger file.

---

lib/units/device/plugins/screen/stream.js

this fix https://github.com/DeviceFarmer/stf/commit/feb77c4396d4209de48779fa855daa382cc11f28.
`broadcastSet.values().map` will return an array of promises. Before the fix, `Promise.settle` will settle for `[[promise0, promise1, ...]]`, so in fact there is no wait for any of the promises at all; after the fix `Promise.settle` will settle for `[promise0, promise1, ...]`, then the callback will only called after all promises are resolved.

fix: Promise.settle's parameter in stream.js
